name: Generate Snake Theme Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # solarized-darkテーマの生成のみをテストする
      - name: Generate solarized-dark snake
        uses: Platane/snk@v3
        with:
          github_user_name: yudai-22
          outputs: dist/snake-solarized-dark.svg?palette=solarized-dark

      # 生成されたファイルをリポジトリにプッシュする
      - name: Push generated file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Test solarized-dark theme generation"
          git push
